# Generated by Django 3.2 on 2021-05-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiker', models.CharField(max_length=15, verbose_name='Тикер')),
            ],
            options={
                'verbose_name': 'Тикер',
                'verbose_name_plural': 'Тикер',
            },
        ),
    ]
