# Generated by Django 3.2 on 2021-05-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='active',
            name='pozition',
            field=models.CharField(choices=[('LG', 'Long'), ('SH', 'Short')], default='LG', max_length=2),
        ),
    ]
