# Generated by Django 3.2 on 2021-05-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_active_pozition'),
    ]

    operations = [
        migrations.AddField(
            model_name='active',
            name='price',
            field=models.FloatField(null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='active',
            name='pozition',
            field=models.CharField(choices=[('лонг', 'Long'), ('шорт', 'Short')], default='лонг', max_length=5),
        ),
    ]
