# Generated by Django 3.2 on 2021-05-26 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210526_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active',
            name='rate',
        ),
    ]
