# Generated by Django 3.2 on 2021-05-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210529_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active',
            name='pozition',
            field=models.CharField(choices=[('купил', 'Купил'), ('продал', 'Продал')], default='купил', max_length=6, verbose_name='Тип позиции'),
        ),
    ]
