# Generated by Django 3.2 on 2021-05-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_active_pozition'),
    ]

    operations = [
        migrations.AddField(
            model_name='active',
            name='test',
            field=models.CharField(default=0, max_length=15, verbose_name='test'),
        ),
    ]
