# Generated by Django 3.2 on 2021-05-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_active_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiker', models.CharField(max_length=15, verbose_name='Тикер')),
                ('pozition', models.CharField(choices=[('купил', 'Купил'), ('продал', 'Продал')], default='купил', max_length=6, verbose_name='Тип позиции')),
                ('quantity', models.FloatField(default=0, null=True, verbose_name='Количество')),
                ('price', models.FloatField(default=0, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Тикер',
                'verbose_name_plural': 'Тикер',
            },
        ),
    ]
