# Generated by Django 3.2 on 2021-05-30 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_active2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Active2',
        ),
    ]
