# Generated by Django 3.2 on 2021-05-31 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_delete_active2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Active',
            new_name='Operation',
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
    ]
