# Generated by Django 3.2 on 2021-05-31 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='active',
            old_name='coin',
            new_name='operation',
        ),
    ]
