# Generated by Django 3.2 on 2021-05-31 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_coin_active_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active',
            name='operation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main.operation'),
        ),
    ]
