# Generated by Django 3.2 on 2021-05-31 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_active_operation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='active',
            options={'verbose_name': 'Актив', 'verbose_name_plural': 'Активы'},
        ),
        migrations.AlterField(
            model_name='active',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.operation'),
        ),
    ]
