# Generated by Django 3.2 on 2021-06-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210531_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='active',
            name='in_pozition',
            field=models.FloatField(default=0, null=True, verbose_name='В позиции'),
        ),
        migrations.AddField(
            model_name='active',
            name='middle',
            field=models.FloatField(default=0, null=True, verbose_name='Средняя'),
        ),
        migrations.AddField(
            model_name='active',
            name='volume',
            field=models.FloatField(default=0, null=True, verbose_name='Объем'),
        ),
    ]
