# Generated by Django 3.2 on 2021-06-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210601_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='price',
            field=models.FloatField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='quantity',
            field=models.FloatField(null=True, verbose_name='Количество'),
        ),
    ]
